namespace BlackJack.BusinessLogic.Enums
{
    public enum BotName
    {
        None = 0,
        Taylor = 1,
        Slyvia = 2,
        Tory = 3,
        Adaline = 4,
        Ellis = 5,
        Danille = 6,
        Dulcie = 7,
        Abe = 8,
        Tawana = 9,
        Sergio = 10,
        Damian = 11,
        Bertram = 12,
        Nanette = 13,
        Irena = 14,
        Adele = 15,
        Deloras = 16,
        Kendra = 17,
        Emory = 18,
        Percy = 19,
        Wilson = 20,
        Michale = 21,
        Fred = 22,
        Stanford = 23,
        Jamey = 24,
        Buck = 25,
        Osvaldo = 26,
        Harold = 27,
        Nevada = 28,
        Janice = 29,
        Arleen = 30,
        Alverta = 31,
        Chantal = 32,
        Darron = 33,
        Federico = 34,
        Arturo = 35,
        Dominic = 36,
        Barton = 37,
        Waylon = 38,
        Alvaro = 39,
        Rufus = 40,
        Myung = 41,
        Madaline = 42,
        Mindi = 43,
        Anabel = 44,
        Merle = 45,
        Doug = 46,
        Samual = 47,
        Lupe = 48,
        Van = 49,
        Jake = 50
    }
}